name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 1: Configurer Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 2: Forcer l'encodage UTF-8 sur les fichiers source
      - name: Set file encoding to UTF-8
        run: |
          find . -type f -exec dos2unix {} \;  # Convertir les fichiers en format UNIX (si nécessaire)
          find . -type f -exec iconv -f WINDOWS-1252 -t UTF-8 -o {} {} \; || echo "No conversion needed"

      # Étape 3: Installer les dépendances et compiler le projet
      - name: Install dependencies and compile
        run: mvn clean install

      # Étape 4: Exécuter les tests
      - name: Run Tests
        run: mvn test

      # Étape 5: (Optionnel) Télécharger les résultats des tests
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
